In [10]:
import pandas as pd
import pymongo

df = pd.read_csv('Daily_Global_Stock_Market_Indicators.csv')
df.head()

,Date,Index_Name,Country,Open,High,Low,Close,Volume,Daily_Change_Percent
0,2020-01-01,S&P 500,USA,15607.06,16277.38,15427.47,16057.78,36788921,2.89
1,2020-01-01,NASDAQ Composite,USA,7083.79,7343.64,6461.54,6641.87,22249687,-6.24
2,2020-01-01,Dow Jones,USA,26384.65,26601.25,25659.50,25941.06,4344769,-1.68
3,2020-01-01,FTSE 100,UK,8091.17,8182.45,7617.15,7774.58,44250411,-3.91
4,2020-01-01,Nikkei 225,Japan,1899.43,2044.17,1885.43,1924.21,22498555,1.30

In [11]:
data = df.to_dict(orient='records')

In [12]:
DB_NAME = "Proj1"
COLLECTION_NAME = "Proj1-Data"
CONNECTION_URL = "mongodb+srv://umangpandittt15_db_user:VbPvgBUT48gyp8rG@cluster0.8fejkha.mongodb.net/?appName=Cluster0"

In [13]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [14]:
rec = collection.insert_many(data)

In [15]:
df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,Date,Index_Name,Country,Open,High,Low,Close,Volume,Daily_Change_Percent
0,6986cad113de77f2fbc5da16,2020-01-01,S&P 500,USA,15607.06,16277.38,15427.47,16057.78,36788921,2.89
1,6986cad113de77f2fbc5da17,2020-01-01,NASDAQ Composite,USA,7083.79,7343.64,6461.54,6641.87,22249687,-6.24